[download]
output_path = 'mods'

[minecraft]
version = "1.18.1"

[fabric]
mods = [
    "fabric-api",
    "krypton",
    "multiconnect",
    "sodium",
    "iris",
    "ferrite-core",
    "lithium",
    "lazydfu",
    "modmenu",
    "starlight",
    "spark",
    "smoothboot-fabric",
    "hydrogen",
    "c2me-fabric",
    "inspecio",
    "lambdynamiclights",
    "lambdabettergrass",
    "advancementinfo",
    "visual-overhaul",
    "charmonium",
    "chime",
    "extrasounds",
    "notenoughcrashes",
    "presence-footsteps",
    "stepup"
]

[forge]
mods = [
    "terra"
]