[minecraft]
version = "1.18.1"

[fabric]
mods = [
    "fabric-api",
    "krypton",
    "multiconnect",
    "sodium",
    "iris",
    "ferrite-core",
    "lithium",
    "lazydfu",
    "modmenu",
    "starlight",
    "spark",
    "smoothboot-fabric",
    "hydrogen"
]